version: "2"

#all machines are connected to the docker 0 network
services:

    database:
        image: mysql:8.0.21
        container_name: database
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_DATABASE=mydatabase
          - MYSQL_USER=user
          - MYSQL_PASSWORD=user-password
          - MYSQL_ROOT_PASSWORD=root-password
        ports:
          - "3306:3306"
          - "33060:33060"
        volumes:
          - ./volumes/data:/var/lib/mysql
        networks:
          - backend_network
        cap_add:
          - SYS_NICE  # CAP_SYS_NICE


    server:
        image: nginx
        container_name: server
        expose:
            - "80/tcp"
        ports:
            - "8080:80"
        volumes:
            - ../frontend/src:/usr/share/nginx/html:ro
        restart: on-failure
        environment:
            - NGINX_PORT=80


    backend:
        build: ../backend-service/
        image: backend-service
        container_name: backend-service
        volumes:
            - ./volumes/uploads:/uploads
            - ./volumes/public/contents:/contents
        environment:
            - PORT=3000
            - DATABASE_NAME=back_database
            - DATABASE_USER=user
            - DATABASE_PASSWORD=user-password
            - DATABASE_HOST=db
            - DATABASE_PORT=3306
            - WAIT_HOSTS=database:3306
        ports:
            - "3000:3000"
        networks:
            - backend_network
        depends_on:
            - database

networks:
    backend_network:
        driver: bridge